## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/EcologicalSemantics for details
sudo: required

services:
  - docker
  
before_install:
  - docker pull obolibrary/odkfull

before_script:
  - cd src/ontology

# command to run tests
script: 
  - sh run.sh make all

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis

### UNCOMMENT THIS AND ADD YOUR DETAILS:
notifications:
  email:
    - annethessen@gmail.com
